apiVersion: v2
name: audit
description: Spydersoft Audit service — processor (RabbitMQ → MongoDB) + query API.
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
- name: common
  version: 4.4.0
  repository: https://bjw-s-labs.github.io/helm-charts
