{{- if .Values.oidc.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongo-express-oidc-secret-es
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mongo-express-oidc-secret
  data:
  - secretKey: client_secret
    remoteRef:
      key: secrets-k8/audit/{{ .Values.vault.environment }}/{{ .Values.oidc.vaultKey }}
      property: client_secret
{{- end }}
