apiVersion: v2
name: mongo-express
description: Mongo Express web UI for the platform MongoDB instance.
type: application
version: 0.1.0
appVersion: "1.0.2"

dependencies:
- name: common
  version: 4.4.0
  repository: https://bjw-s-labs.github.io/helm-charts
