defaultPodOptions:
  imagePullSecrets:
    - name: cr-spydersoft-github

controllers:
  filestore-api:
    enabled: true
    type: deployment
    replicas: 1
    revisionHistoryLimit: 1
    strategy: RollingUpdate
    containers:
      main:
        image:
          repository: ghcr.io/spydersoft-consulting/filestore-api
          pullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              identifier: filestore-api
          - secretRef:
              name: filestore-secrets
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet: { path: /livez, port: 8080 }
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet: { path: /readyz, port: 8080 }
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3

service:
  filestore-api:
    enabled: true
    controller: filestore-api
    nameOverride: filestore-api
    primary: true
    type: ClusterIP
    ports:
      http:
        enabled: true
        primary: true
        port: 80
        targetPort: 8080

route:
  filestore-api:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: main
        namespace: envoy-gateway-system
        group: gateway.networking.k8s.io
        kind: Gateway
    rules:
      - matches:
          - path: { type: PathPrefix, value: / }
        backendRefs:
          - identifier: filestore-api
            port: 80

vault:
  environment: ""
