apiVersion: v2
name: mongodb
description: Single-node MongoDB for Spydersoft platform services (audit log).
type: application
version: 0.1.0
appVersion: "7.0"

dependencies:
- name: common
  version: 4.4.0
  repository: https://bjw-s-labs.github.io/helm-charts
